version: '3.8'

services:
  # AT Protocol HMA Integration Service
  atproto-hma:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/atproto_hma
      - HMA_API_URL=http://hma:5000
      - LOG_LEVEL=INFO
      - PORT=3000
      - HOST=0.0.0.0
      - WORKERS=4
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
      - hma
    restart: unless-stopped
    networks:
      - atproto-hma-network

  # HMA Service
  hma:
    image: ghcr.io/facebook/hasher-matcher-actioner:latest
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=hma
      - OMM_CONFIG=/build/reference_omm_configs/development_omm_config.py
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - atproto-hma-network

  # Database
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=atproto_hma,hma
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-multiple-pg-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-pg-dbs.sh
    restart: unless-stopped
    networks:
      - atproto-hma-network

volumes:
  postgres-data:

networks:
  atproto-hma-network:
    driver: bridge 