version: '3'

services:
  # HMA Service with modified entrypoint for debugging
  hma-debug:
    image: ghcr.io/facebook/threatexchange/hma:latest
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=media_match
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=media_match
      - OMM_CONFIG=/build/reference_omm_configs/development_omm_config.py
      - POSTGRES_CONNECTION_STRING=postgresql://media_match:hunter2@db:5432/media_match
      - SQL_ALCHEMY_DATABASE_URI=postgresql://media_match:hunter2@db:5432/media_match
      - FLASK_APP=OpenMediaMatch.app
    entrypoint: ["sleep", "infinity"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hma-network

networks:
  hma-network:
    external: true 