version: "3"

x-postgres-variables: &postgres-variables
  POSTGRES_USER: media_match
  # TODO: Use a secret instead.
  POSTGRES_PASSWORD: hunter2
  POSTGRES_HOST: db
  POSTGRES_DBNAME: media_match

services:
  app:
    image: ghcr.io/facebook/threatexchange/hma:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      <<: *postgres-variables
      OMM_CONFIG: /build/reference_omm_configs/development_omm_config.py
    depends_on:
      - db
    networks:
      - backend
    command: >
      bash -c "MIGRATION_COMMAND=1 flask --app OpenMediaMatch.app db upgrade --directory OpenMediaMatch/migrations 
      && MIGRATION_COMMAND=0 flask --app OpenMediaMatch.app run --host=0.0.0.0 --debug"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - ./scripts/init-multiple-pg-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-pg-dbs.sh
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      <<: *postgres-variables
      POSTGRES_MULTIPLE_DATABASES: media_match,atproto_hma
    networks:
      - backend

  # ATProto-HMA Bridge service
  atproto-hma:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://media_match:hunter2@db:5432/atproto_hma
      HMA_API_URL: http://app:5000
      HMA_API_KEY: dev_key
      LOG_LEVEL: INFO
      PORT: 3000
      HOST: 0.0.0.0
    depends_on:
      - app
      - db
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge 